import fs from 'node:fs/promises';import {createRequire} from 'node:module';
const require=createRequire('C:/Users/Vitor/AppData/Local/npm-cache/_npx/0f94ee7615faf582/node_modules/a.cjs');
const {startFlow}=await import('file:///C:/Users/Vitor/AppData/Local/npm-cache/_npx/0f94ee7615faf582/node_modules/lighthouse/core/index.js');
const browser=await require('puppeteer-core').launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const dir='C:/Users/Vitor/Desktop/sites-wordpress/jk-marmores-configurador/docs/auditorias/configurador-design-2026-09-28',label=process.argv[2]??'b',results=[],sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{for(const width of [390,1440]){
const page=await browser.newPage();await page.setViewport({width,height:width===390?844:900,isMobile:width===390,hasTouch:width===390});await page.goto('http://127.0.0.1:3107/',{waitUntil:'networkidle0'});await page.$eval('[data-configurador]',e=>e.scrollIntoView());await page.waitForSelector('[data-immersive] canvas[data-frame]');await sleep(1400);
const flow=await startFlow(page,{name:`Configurador ${label} ${width}`,configContext:{settingsOverrides:{onlyCategories:['accessibility'],screenEmulation:{disabled:true},formFactor:width===390?'mobile':'desktop'}}});await flow.snapshot({stepName:'Palco visível'});if(width===390){await page.click('button[aria-controls]');await sleep(450);await flow.snapshot({stepName:'Gaveta aberta'});}const result=await flow.createFlowResult();results.push({width,steps:result.steps.map(s=>({name:s.name,score:s.lhr.categories.accessibility.score,failures:Object.values(s.lhr.audits).filter(a=>a.score===0).map(a=>({id:a.id,title:a.title,details:a.details}))}))});await page.close();
}
const page=await browser.newPage();await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await page.evaluateOnNewDocument(()=>{Element.prototype.requestFullscreen=undefined;});await page.goto('http://127.0.0.1:3107/',{waitUntil:'networkidle0'});await page.$eval('[data-configurador]',e=>e.scrollIntoView());await page.waitForSelector('[data-immersive]');await sleep(1600);await page.evaluate(()=>[...document.querySelectorAll('[data-immersive] button')].find(e=>e.textContent.trim()==='Tela cheia').click());await sleep(350);const expanded=await page.$eval('[data-immersive]',e=>({role:e.getAttribute('role'),modal:e.getAttribute('aria-modal'),height:e.getBoundingClientRect().height,window:innerHeight}));await page.keyboard.press('Escape');await sleep(350);const exit=await page.evaluate(()=>({full:document.querySelector('[data-immersive]').dataset.fullscreen,focused:document.activeElement.textContent,overflow:document.body.style.overflow,hintStored:localStorage.getItem('jk-configurador-gestos-v1')}));results.push({fallback:{expanded,exit}});await page.close();
}finally{await browser.close();await fs.writeFile(`${dir}/${label}-lighthouse.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results));}
